### ISSUE TITLE
Asking for Maintainer access

### ISSUE THREAD

**Issue by omareldardear** [robotology/logpolar#4]
Ciao @pattacini 

Can you grant me full access to this library? 
I am the one responsible for it at the moment together with @reafrancesco 

Thanks

**Comment by pattacini** [comment]
Hi @omareldardear 

I've just made @reafrancesco admin of this repo.
He can now grant you the access you need.

**Comment by pattacini** [comment]
Just granted you write access as of now.
As said, @reafrancesco can fine-tune your permissions.
